# Generated by Django 3.1 on 2020-09-25 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200916_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.TextField(default='text'),
        ),
    ]
