# Generated by Django 3.1 on 2020-10-17 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_message_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendedContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='friends',
        ),
        migrations.AddField(
            model_name='chat',
            name='chatType',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='phoneNumber',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='FriendedContact',
        ),
        migrations.AddField(
            model_name='friendedcontacts',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friended_contacts', to='chat.contact'),
        ),
        migrations.AddField(
            model_name='friendedcontacts',
            name='friends',
            field=models.ManyToManyField(blank=True, to='chat.Contact'),
        ),
    ]
