# Generated by Django 3.1 on 2020-10-30 16:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0008_contact_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendedcontacts',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
