# Generated by Django 3.1 on 2020-10-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20201030_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendedcontacts',
            name='friends',
            field=models.ManyToManyField(blank=True, to='chat.Contact'),
        ),
    ]
