# Generated by Django 3.1 on 2020-10-31 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20201030_1712'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FriendedContacts',
        ),
    ]
