# Generated by Django 3.1 on 2020-10-31 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_friends_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends',
            name='slug',
            field=models.SlugField(),
        ),
    ]
