# Generated by Django 3.1 on 2020-11-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_auto_20201103_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='chatName',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='chatPicture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
