# Generated by Django 3.1 on 2020-11-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_auto_20201103_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='admins',
            field=models.ManyToManyField(to='chat.Contact'),
        ),
    ]
